#include "CountryMap.h"

const QHash<QString, QString>& CountryMap::nameToIso() {
    static const QHash<QString, QString> map = {
        { "Afghanistan",               "af" },
        { "Albania",                   "al" },
        { "Algeria",                   "dz" },
        { "Argentina",                 "ar" },
        { "Australia",                 "au" },
        { "Austria",                   "at" },
        { "Bangladesh",                "bd" },
        { "Belgium",                   "be" },
        { "Brazil",                    "br" },
        { "Canada",                    "ca" },
        { "China",                     "cn" },
        { "Colombia",                  "co" },
        { "Czech Republic",            "cz" },
        { "Denmark",                   "dk" },
        { "Egypt",                     "eg" },
        { "Finland",                   "fi" },
        { "France",                    "fr" },
        { "Germany",                   "de" },
        { "Ghana",                     "gh" },
        { "Greece",                    "gr" },
        { "Hungary",                   "hu" },
        { "India",                     "in" },
        { "Indonesia",                 "id" },
        { "Iran",                      "ir" },
        { "Iraq",                      "iq" },
        { "Ireland",                   "ie" },
        { "Israel",                    "il" },
        { "Italy",                     "it" },
        { "Japan",                     "jp" },
        { "Kenya",                     "ke" },
        { "Malaysia",                  "my" },
        { "Mexico",                    "mx" },
        { "Netherlands",               "nl" },
        { "New Zealand",               "nz" },
        { "Nigeria",                   "ng" },
        { "Norway",                    "no" },
        { "Pakistan",                  "pk" },
        { "Peru",                      "pe" },
        { "Philippines",               "ph" },
        { "Poland",                    "pl" },
        { "Portugal",                  "pt" },
        { "Romania",                   "ro" },
        { "Russia",                    "ru" },
        { "Saudi Arabia",              "sa" },
        { "South Africa",              "za" },
        { "South Korea",               "kr" },
        { "Spain",                     "es" },
        { "Sweden",                    "se" },
        { "Switzerland",               "ch" },
        { "Thailand",                  "th" },
        { "Turkey",                    "tr" },
        { "Ukraine",                   "ua" },
        { "United Arab Emirates",      "ae" },
        { "United Kingdom",            "gb" },
        { "United States",             "us" },
        { "Vietnam",                   "vn" }
    };
    return map;
}
